/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tuanche_app_utils_Validator */

#ifndef _Included_com_tuanche_askforanswer_app_utils_Validator
#define _Included_com_tuanche_askforanswer_app_utils_Validator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tuanche_app_utils_Validator
 * Method:    signNativeMethod
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tuanche_askforanswer_app_utils_Validator_signNativeMethod
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_tuanche_app_utils_Validator
 * Method:    getSafeSign
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tuanche_askforanswer_app_utils_Validator_getSafeSign
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tuanche_app_utils_Validator
 * Method:    decodeSafeSign
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tuanche_askforanswer_app_utils_Validator_decodeSafeSign
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tuanche_app_utils_Validator
 * Method:    getSafeKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tuanche_askforanswer_app_utils_Validator_getSafeKey
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
